version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular:8.0.0
    container_name: scott_web_app
    command: npm run start:all
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 4000:4000
    volumes:
      - .:/opt/app

networks:
  default:
    name: wtf_network
